package modules

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/specter-recon/recon-tool/core"
)

// MasscanEntry represents a single JSON record generated by Masscan (-oJ).
type MasscanEntry struct {
	IP        string        `json:"ip"`
	Timestamp string        `json:"timestamp"`
	Ports     []MasscanPort `json:"ports"`
}

type MasscanPort struct {
	Port   int    `json:"port"`
	Proto  string `json:"proto"`
	Status string `json:"status"`
	Reason string `json:"reason"`
	TTL    int    `json:"ttl"`
}

// ParseMasscanJSON parses Masscan JSON data into HostInfo and PortInfo slices.
func ParseMasscanJSON(data []byte) ([]core.HostInfo, []core.PortInfo, error) {
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) == 0 {
		return nil, nil, nil
	}

	var entries []MasscanEntry

	// Attempt 1: Standard JSON Array
	if err := json.Unmarshal(trimmed, &entries); err == nil && len(entries) > 0 {
		return processMasscanEntries(entries)
	}

	// Attempt 2: Clean up streaming JSON trailing comma/brackets
	cleaned := trimmed
	if bytes.HasPrefix(cleaned, []byte("[")) && !bytes.HasSuffix(cleaned, []byte("]")) {
		cleaned = append(cleaned, ']')
	}
	if bytes.HasSuffix(cleaned, []byte(",\n]")) || bytes.HasSuffix(cleaned, []byte(",]")) {
		cleaned = bytes.Replace(cleaned, []byte(",]"), []byte("]"), -1)
		cleaned = bytes.Replace(cleaned, []byte(",\n]"), []byte("\n]"), -1)
	}
	if err := json.Unmarshal(cleaned, &entries); err == nil && len(entries) > 0 {
		return processMasscanEntries(entries)
	}

	// Attempt 3: Line-by-Line JSON or Masscan text format
	scanner := bufio.NewScanner(bytes.NewReader(trimmed))
	var lineEntries []MasscanEntry
	var textPorts []core.PortInfo
	seenHosts := make(map[string]bool)
	var hosts []core.HostInfo

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		line = strings.TrimSuffix(line, ",")
		if line == "" || line == "[" || line == "]" || strings.HasPrefix(line, "#") {
			continue
		}

		var singleEntry MasscanEntry
		if err := json.Unmarshal([]byte(line), &singleEntry); err == nil && singleEntry.IP != "" {
			lineEntries = append(lineEntries, singleEntry)
			continue
		}

		// Text format: "open tcp 80 192.168.1.1 1610000000" or "Discovered open port 80/tcp on 192.168.1.1"
		fields := strings.Fields(line)
		if len(fields) >= 4 && (fields[0] == "open" || fields[0] == "Discovered") {
			var ip string
			var portNum int
			var proto string = "tcp"

			if fields[0] == "open" {
				proto = strings.ToLower(fields[1])
				p, errP := strconv.Atoi(fields[2])
				if errP == nil {
					portNum = p
					ip = fields[3]
				}
			} else if fields[0] == "Discovered" && len(fields) >= 6 {
				// Discovered open port 80/tcp on 192.168.1.1
				pParts := strings.Split(fields[3], "/")
				if len(pParts) >= 1 {
					p, errP := strconv.Atoi(pParts[0])
					if errP == nil {
						portNum = p
						if len(pParts) > 1 {
							proto = strings.ToLower(pParts[1])
						}
						ip = fields[5]
					}
				}
			}

			if ip != "" && portNum > 0 {
				if !seenHosts[ip] {
					seenHosts[ip] = true
					hosts = append(hosts, core.NewHostInfo(ip, "masscan_list"))
				}
				textPorts = append(textPorts, core.PortInfo{
					IP:          ip,
					Port:        portNum,
					Protocol:    proto,
					State:       "open",
					ServiceName: GuessServiceName(portNum),
					Source:      "masscan",
					Verified:    false,
					Conflict:    false,
				})
			}
		}
	}

	if len(lineEntries) > 0 {
		return processMasscanEntries(lineEntries)
	}

	if len(textPorts) > 0 {
		return hosts, textPorts, nil
	}

	return nil, nil, fmt.Errorf("masscan çıktısı ayrıştırılamadı (geçersiz JSON/format)")
}

func processMasscanEntries(entries []MasscanEntry) ([]core.HostInfo, []core.PortInfo, error) {
	seenHosts := make(map[string]bool)
	var hosts []core.HostInfo
	var ports []core.PortInfo

	for _, entry := range entries {
		if entry.IP == "" {
			continue
		}
		if !seenHosts[entry.IP] {
			seenHosts[entry.IP] = true
			hosts = append(hosts, core.NewHostInfo(entry.IP, "masscan_json"))
		}

		for _, p := range entry.Ports {
			if p.Status != "open" && p.Status != "" {
				continue
			}
			proto := strings.ToLower(p.Proto)
			if proto == "" {
				proto = "tcp"
			}

			ports = append(ports, core.PortInfo{
				IP:          entry.IP,
				Port:        p.Port,
				Protocol:    proto,
				State:       "open",
				ServiceName: GuessServiceName(p.Port),
				Source:      "masscan",
				Verified:    false,
				Conflict:    false,
			})
		}
	}

	return hosts, ports, nil
}

// LoadMasscanJSONFile reads and parses a Masscan output file.
func LoadMasscanJSONFile(filePath string) ([]core.HostInfo, []core.PortInfo, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, nil, fmt.Errorf("masscan dosyası okunamadı (%s): %w", filePath, err)
	}
	return ParseMasscanJSON(data)
}
